### ISSUE TITLE
USB-C without case modification

### ISSUE THREAD

**Issue by edwardxia** [stefan-ess/hhkb_controller#1]
Thanks for the great work.

Apparently, there’s a cleaver way to fit the USB-C port in the existing cut of mini-USB: https://github.com/manisteinn/usb-type-c-hhkb

Hasu is making a similar implementation available: https://geekhack.org/index.php?topic=103495.0

> Type-C connector is implemented on castellated daughter pcb to tune its height to the existent opening.

Would you consider it in the next iteration?

**Comment by 4pplet** [comment]
Thanks for showing interest in the project!

Yes, I have seen that solution and I agree, it is clever and really nice that there is no need to modify the case.

While that is a neat solution, I do not think it will work on this board, this due to the very tight tolerances for USB3 traces. In the hasu controller, they run regular USB2.0, where signal impedance matching etc is a lot less critical.

Preferably, I'd like to find a USB-C connector for USB3 that sit a bit higher than my current one, so that there is no need to modify the case, but I have yet to find one that is suitable.

Cheers!

**Comment by edwardxia** [comment]
https://www.mouser.com/datasheet/2/206/J119851-1499861.pdf

https://www.mouser.com/datasheet/2/222/KUSBX-SMTTH-CSE-1621703.pdf

I’m not familiar with hardware at all, but any chance one of these kinds may work?

**Comment by 4pplet** [comment]
I think the connector you linked will end up a bit too high, and thus will need modification anyway, I'll look in to it closer.

The connector will work considering the other aspects I think (PCB thickness etc), tho it will be a bit more of a pain to solder, since it has SMD-pads that is hidden by the connector.
